module.exports = Object.freeze({
  //Power of Thoughts
  1: "Success has a price. There is no such thing as “getting something for nothing.”",
  2: "Achievement and greatness begin with ideas. If you have an idea, you are already halfway to success.",
  3: "Thoughts can translate into actions. With desire, belief, and persistence, you can translate your thoughts into successes.",
  4: "When you truly desire something, you will achieve it.",
  5: "If you are determined, have a strong desire, and a willingness to put everything on the line to fulfill your purpose, opportunities will come to you from various directions and perspectives. So, seize every opportunity needed to achieve your goal(s) and fulfill your purpose in life.",
  6: "Your goals and desires can be translated into monetary and non-monetary wealth. So, never stop taking steps towards your goal(s), even if others doubt you.",
  7: "You may experience many failures and defeats and they may make you feel as if you want to give up.  Don’t. Allow each failure to strengthen your desire(s) and use each defeat as a stepping stone towards success.",
  8: "Look at failures as “practice shots.” All successful people fail at some point in their lives.",
  9: "If you are “success conscious,” you will be successful. Focused thoughts and feelings can help you become “success conscious.”",
  10: "The term “impossible” doesn’t exist. Things there were “impossible” one day can be “possible” the next. So, never say never.  As long as you are breathing anything is “possible.”",
  11: "If you truly want something, you will have it. Success comes from desire, persistence, and determination.",
  12: "Key strategic planning aspects in complicated large projects or new technologies should involve four important elements: (1) identifying the things you want to accomplish, (2) having faith that you can and will achieve your goal(s), (3) being able to visualize success, and (4) being persistent until you finally reach your goal(s).",
  13: "When you have a strong desire to be successful, it is easier to become “success conscious.” Being “success conscious” means you are determined to develop a resilient plan that will help you achieve your goal(s).",
  14: "If you have a strong desire to achieve your goal(s), you will accomplish them.",
  //Purpose, Desires, Goals
  15: "The starting point of all achievements is determining your life purpose.",
  16: "Your life purpose can help you develop the strong desires needed to propel you towards greatness. So, identify your purpose and passions, and what you’d like to accomplish.",
  17: "Say aloud, “I will do whatever it takes to achieve my goals and desires.” Life gives you what you ask for.",
  18: "Your desires should coincide with an obsession to be successful. Dreams begin with creating a strong desire to accomplish something.",
  19: "Picturing yourself as successful can help you manage your thoughts and actions.",
  20: "Imagining yourself as successful and visualizing the person you want to be can help you achieve your goal(s). Practicing daily affirmations can help you “override” your subconscious mind, which controls at least 95% of your daily activities.",
  21: "Set time aside each day to just be alone and undisturbed. Get comfortable and relax. Then, start visualizing the person you want to be. This will help you “override” your subconscious mind, which researchers say controls at least 95% of your daily activities.",
  22: "Reflect on your past successes. Every success - big or small. Use this as “proof” that you are capable of being successful. Don’t forget to celebrate each success. When you lose faith in yourself, think about your past successes.",
  23: "Set concrete goals. Have a clear direction of where you want to go. If you start to deviate from this direction, take immediate corrective actions.",
  24: "If you truly believe in your goal(s), you will achieve them.",
  25: "A person who wins, effectively burns the “bridge” that would allow him or her to return to his or her “old ways”. Have a strong desire to achieve your goal(s) and keep moving forward!",
  26: "Your purpose is your destination, and your goals and desires are your stepping stones to get there.",
  27: "6 steps to turn goals and desires into successes: \r\n1. Identify your goal(s) and desire(s).\r\n2. Determine exactly what you will give in return.\r\n3. Establish a concrete date to achieve your goal(s).\r\n4. Create a realistic plan to accomplish your goal(s) and ready or not, begin it now!\r\n5. Document all of your goals.\r\n6. Review your goal(s) at least twice daily in the form of positive affirmations. Review them aloud 1x in the morning and 1x at night. Imagine that you have already accomplished your goal(s) to “override” your subconscious mind and convince yourself that you are capable of success. \r\n*These steps only require imagination and persistence.",
  28: "Researchers suggest that having defined goals, writing them down, and saying them aloud can significantly increase the probability that you will achieve them.",
  29: "Every failure brings equivalent success in some way. Keep in mind that Thomas Edison failed 10,000 times before successfully inventing the light bulb.",
  30: "Your failures are your most valuable assets. Use them to strengthen your persistence.",
  31: "Stop thinking about losses. Thinking about losses only brings more losses. Thinking about winning only brings more winning. These theories are psychologically-proven.",
  32: "All successful stories follow the same pattern - dreams followed by failures - follow by successes.",
  33: "Make your state-of-mind an “absolute belief” that you will achieve your desire(s) and goal(s). Stay away from a “maybe” state-of-mind.",
  34: "The strength of your desire, along with believing in yourself, can outweigh Mother Nature and turn your dreams into reality. There is no such thing as “impossible.”",
  //Self Belief
  35: "Your only limitations are the ones you have created.",
  36: "To be more confident, you’ll need to have faith and truly believe in yourself. Always visualize yourself as someone who has already achieved his or her goal(s).",
  37: "People create their own misfortunes or “bad luck” by not having faith in their abilities. Believe in yourself.",
  38: "Pass on positive thoughts from your conscious mind to your subconscious one, through daily affirmations and believing in yourself.",
  39: "Plant your ideas in your subconscious mind using positive thoughts. Do this without doubt because doubt will them cancel out. Once these ideas enter your subconscious mind, positive things will begin to happen for you.",
  40: "Believe in yourself! Belief is the foundation of all miracles. You can boost your self-confidence by believing in yourself and having a strong desire to accomplish your goals. Having this mentality enables you to have a much higher intelligence, which allows you create specific steps to achieve your goal(s).",
  41: "The real magic of affirmations lies in repeating positive statements continuously. Your subconscious mind will eventually believe that what you are saying is, in fact, true. Once this occurs, you will be driven to take the necessary steps to achieve your goals.",
  42: "Positive thoughts and emotions work are like magnetics attracting similar positive thoughts and emotions to you.",
  43: "A negative attitude won’t help you accomplish your goals. However, a positive attitude will attract positivity towards you.",
  44: "Negative thinking destroys your subconsciousness. While positive thinking (affirmations) helps you achieve a higher intelligence.",
  45: "Success begins with a simple thought, so control your thoughts and believe in your in abilities to fulfill your desires.",
  46: "Focus your thoughts for 10-15 minutes daily; visualizing the person you want to be. Create a clear mental picture of the person you “see” in your mind.  Your subconscious mind will eventually accept it and start “feeding” your conscious mind the “food” it needs to achieve your goal(s).",
  47: "Improve your self-confidence through positive affirmations. Repeat your goal(s), desires, and/or purpose in life for at least 10 minutes each day.",
  48: "Negative thoughts only attract more negativity and misery. Positive thoughts only attract positivity and happiness. So, be positive and believe in yourself.",
  //Affirmations
  49: "Quitters never win and winners never quit.",
  50: "Exercise the control over your subconscious mind, through positive affirmations (positive thinking).",
  51: "Your subconscious mind stores everything you have ever experienced. It performs this function – even if you don’t want it to. However, you can control its intake by focusing on daily affirmations and visualization (imagining your success).",
  52: "Studies suggest that positive self-affirmations can help you achieve your goal(s).",
  53: "Practice this visualization exercise daily - close your eyes and imagine that you have already achieved your goal. The goal of this exercise is to make yourself to truly believe you are successful.",
  54: "Start working on your goal(s) immediately and do not wait for a complete plan! As your mind concocts parts of the plan, act on it right away and use the power of your subconscious mind to propel you towards a higher intelligence. Do not completely rely, however, on your conscious mind because it may become lazy. Rather, rely on your subconscious mind, through visualization and imagination.",
  55: "Visualizing the person you want to be, while closing your eyes is a powerful technique that is also widely used in sports.",
  56: "Place visuals in front of you for positive empowerment. These visuals may include: company logos, vision boards, etc. Use visuals that will positively impact your emotions and encourage your subconscious mind to form a plan that will help you achieve your goal(s).",
  //Knowledge
  57: "There are two types of knowledge - general and specialized. Rely on these forms of knowledge to achieve your goal(s).",
  58: "Knowledge begins as a “potential power,” however it becomes a “real power” once it has been put into use, through success, accomplishment, monetary value, etc.",
  59: "An “effective team” is not simple a “work group” that requires collaboration – it is a group of people with same agenda or similar goals or desires. Surround yourself with the “right team” to turn your goal(s) and desire(s) into reality.",
  60: "A person who can direct a team of people is equivalent to a person who has team members with education and knowledge. \r\nThe person who can direct a team of people is equivalent to the person who has all of team members education and knowledge.",
  61: "Decide the type of knowledge you need based on your goal(s) and desire(s). Understand that there are numerous ways to acquire knowledge, such as education, experience, special training, courses, libraries, etc.",
  62: "To be successful, never stop acquiring the knowledge needed to attain your goal(s) and desire(s).",
  63: "Studies suggest that emotional intelligence is a stronger indicator for success, than numerical indicators, such as SAT or IQ. Leaders with a high emotional intelligence typically have more successes, than those with only a high IQ.",
  64: "Set your own limitations and rise to the occasion. To be successful, you will need to continuously gain knowledge.",
  65: "Understand that your ideas, desires, goals, and knowledge are needed to be successful.",
  //Imagination?
  66: "Ideas are products of your imagination. Imagination turns ideas into success, because this is where your goals and desires get refined.",
  67: "The more you use your imagination, the more your imagination will grow. There are two types of imagination - synthetic and creative. Synthetic imagination involves old concepts, ideas, plans, and observations. Most inventors use this type of imagination. Creative imagination involves a much higher intelligence. It automatically occurs when your subconscious mind receives input from your conscious mind.",
  68: "You can translate your ideas into success, through purpose and an execution plan.",
  69: "The simpler the idea or invention, the more it can be adapted.",
  70: "People will say it is waste of time to work on your goal(s); however, a strong desire can keep you moving forward.",
  //Planning
  71: "Share with others what you intend to do, but use your plan to show your vision and progress.",
  72: "For a team to be harmonious each member must determine what he or she wants to do and what he or she wants to achieve.",
  73: "An effective team is one that harmoniously works together. The key principle of having a harmonious team is having common values or interests. When you have a harmonious team, the subconscious and conscious minds of the team members connect to each other and create a higher collective intelligence.",
  74: "Develop a practical plan with your team. The team can be as small as 2 or 3 people or as big as +30. Then, interact about twice a week (until everyone has clear roles and responsibilities and is working harmoniously).",
  75: "Develop a plan and get it approved by your team.",
  76: "If your plan does not work, re-adjust it and keep trying. During this time, you may experience failures. Remember, temporary defeats are natural and healthy. So, adjust and keep going.  But, do not quit.",
  77: "Remember, you cannot have success without failure.",
  78: "If you give up before you reach your goal, you are a quitter. Quitters never win and winners never quit.",
  79: "Some of the key qualities of a great leader are: self-control, self confidence in his or her knowledge, cooperation, a solid execution plan, command and justice, decisiveness, going beyond what is expected, charisma, sympathy and understanding, attention to details, and a willingness to assume full responsibility.",
  80: "Key qualities of bad leadership include: a strong emphasis on one’s “title,” a strong emphasis on authority, insecurities, unorganized planning, arrogance, an unrealistic pay expectations based on what you know, instead of what you are tasked to do, a limited imagination, selfishness, unrestraint, and deception.",
  81: "Leadership with cooperation is more effective than leadership by force. Leadership by force is always temporary.",
  82: "A manager does things right, but a leader does the right thing.",
  83: "Prepare your plan and continue to improve it.",
  84: "To have a successful plan, you must consider the quality and quantity of your services, your motivational level, and your team’s collaboration and harmony levels.",
  85: "Perform a plan assessment to determine your weekly, monthly, or annual progress.  Then, set corrective actions.",
  86: "Develop 30, 60, and 90-day plans. Then, ask your team for feedback. Continue to refine these plans until they put you on the path to success.",
  87: "Create a one-year strategic plan. Then, ask your team for feedback. Continue to refine this plan until it puts you on the path to success.",
  //Decisiveness
  88: "Be decisive. Indecisiveness, delayed or slow actions or procrastination are reasons why people fail.",
  89: "Reaching quick decisions is very important because failures can translate into wins.",
  90: "Opinions are “cheap commodities.” If you are highly influenced, you will not reach your goal(s). Keep in mind that friends and loved ones can destroy your confidence. So, quietly pursue your goal(s) and gain the necessary knowledge to fulfill your desires.",
  91: "Do not take too long to make decisions.",
  92: "Use caution when sharing your plans with other people, because one of them could steal it.",
  93: "Develop a realistic plan. Then, share it with others, through your actions - not just your words.",
  94: "People who make quick and firm decisions are more likely to be successful.",
  95: "Be decisive. Decisiveness requires courage.",
  //Determination
  96: "You can’t be successful without making sacrifices.",
  97: "It is common to quit before reaching a goal. Do the opposite. Keep going until you succeed.",
  98: "Giving up is a common weakness amongst many people.",
  99: "Your strength of persistence will depend on your goal(s) or desire(s). Weak desires yield weak results. Strong desires yields strong results.",
  100: "Success and a good consciousness stem from persistence. On the flip side, failure and a poor subconsciousness do not require persistence. Be persistent until you achieve your goal(s)!",
  101: "Be persistent. It does not matter how slow you are because with persistence comes success.",
  102: "Persistence surpasses failure.",
  103: "If you do not have persistence, you will not get where you want to go.",
  104: "A weakness you must overcome and master is a failure to identify what you want.",
  105: "A weakness you must overcome and master is procrastination.",
  106: "A weakness you must overcome and master is a disinterest in gaining the specialized knowledge needed to succeed.",
  107: "A weakness you must overcome and master is indecision and avoidance.",
  108: "A weakness you must overcome and master is a reliance on excuses.",
  109: "A weakness you must overcome and master is self-satisfaction.",
  110: "A weakness you must overcome and master is stubbornness or indifference towards others.",
  111: "A weakness you must overcome and master is a habit of blaming of other for your mistakes.",
  112: "A weakness you must overcome and master is weak goal(s) or desire(s).",
  113: "A weakness you must overcome and master is complaining after a defeat.",
  114: "A weakness you must overcome and master is a lack of planning.",
  115: "A weakness you must overcome and master is a habit of delaying or avoiding action when opportunities present themselves.",
  116: "A weakness you must overcome and master is “wishing” instead of “being willing.”",
  117: "A weakness you must overcome and master is the habit of “settling,” instead of “aiming for success.”",
  118: "A weakness you must overcome and master is seeking shortcuts to success.",
  119: "A weakness you must overcome and master is a fear of criticism.",
  120: "Do not depend on “luck.” When people see your enthusiasm, they will want to help you.",
  121: "Success does not come from “wishes.” It comes from strong desires and solid plans.",
  122: "To develop a strong persistence, you must to have a strong desire, a solid plan, and an effective method that blocks negative influences and helps you connect with people who will encourage your plans and purpose.",
  123: "Persistence can help you master difficulties.",
  //Team
  124: "Key sources of knowledge include: a higher collective team intelligence, through subconscious minds, accumulated experiences, experimentation, and research.",
  125: "Gaining power and value from your team require creating harmony to fulfill common or similar desires.",
  126: "Teams provide two types of valuable powers - economic and intellectual power. Economic team power is achieved through advice and cooperation. Intellectual power involves the mind of the team. It is the feeling you get when you work with other people, while being in-tune with them. This helps you achieve more.",
  127: "The intellectual power that you receive from your team involves the magnitude of energies gleaned from the multiple minds. For example, if your brain is considered a “battery,” then working as a team is the battery connection needed to achieve a higher energy.",
  128: "The most successful people are able to develop teams or “friendly alliances” with each other people.",
  129: "Team members should have two qualities – a willingness to do the job and a willingness to embrace a common spirit of mind.",
  130: "A team must stick to a code of confidentiality. But, do not force members to connect too quickly. Rather, give them time to adapt to each other. Play devil's advocate to challenge the team.",
  131: "To have a harmonious team, each member must determine what he or she wants to do or what he or she wants to achieve.",
  132: "A leader must inspire his or her team.",
  133: "Share what you want to achieve with your spouse and loved ones. Develop a team and alliance with your family, if possible.",
  134: "Positive thinking, a strong persistence, and solid planning can attract success to you.",
  //Motivational Forces
  135: "Love is one of the most powerful human motivational forces that can give you power and courage.",
  136: "Personal magnetism is achieved through charisma.",
  137: "Charisma is projected through a handshake, your voice tone, clothing style, and spirit.",
  138: "Genius comes from knowledge - not ordinary thoughts.",
  139: "“Sixth sense” is a creative imagination that is rarely used. Your “sixth sense” can propel you into action, especially when your other five senses are no longer “hungry.”",
  140: "The more you use your creative imagination, the more defined it gets. When your conscious mind operates from your subconsciousness, you become more creative and imaginative. For example, when a person closes his or her eyes, he or she looks at his or her ideas or thoughts, through a superior intelligence. It is better to achieve this vision with your eyes closed versus when they are open.",
  141: "One way to trigger your genius is to concentrate on the “known” part of your idea or plan. If you can do that, the “unknown” part will eventually be created. Your subconscious mind will analyze the “unknown” parts and develop a solution. Sometimes, the results are positive and sometimes they are negative. FYI: It took Tom Edison 10,000 “tries” before he successfully created the light bulb.",
  142: "Focus on the positive thoughts and emotions that come to your mind. Once you do this, your consciousness and subconsciousness will connect and create genius ideas.",
  //The Mind
  143: "Your subconscious mind works day and night. It never stops. It develops in the womb and continuous to reshape until you reach 6 or 7 years old. However, there are ways to “override” your subconscious mind, if need be, through positive affirmations, positive thinking, and hypnosis.",
  144: "Positive affirmations “feed” your subconscious mind. So, document your goals, practice repetitions, visualize, and behave as if you have already accomplished your goal(s).",
  145: "Your subconscious mind is the “gateway” to a higher intelligence. Once you embrace the positive thoughts and emotions that enter your mind, your conscious and subconscious minds will connect and create genius ideas.",
  146: "One way to “override” your subconscious mind is to focus on positive habits and affirmations, and not rely too much on logic (which lives in your conscious mind).  Understand that forming these habits will not happen immediately. Rather, they will come with practice and persistence.",
  147: "Your subconscious mind can analyze data from your conscious mind and translate it into a higher intelligence.",
  148: "Use the power of your subconscious mind by “feeding” it the right information, such as your purpose, goals and desires. Use positive affirmations and visualizations to accomplish this task.",
  149: "Keep “planting” the idea that you will be successful, through your positive affirmations and visualizations. Your subconscious mind will accept them and start “feeding” your conscious mind with the actions needed to achieve your purpose, goals, and desires.",
  150: "Shut-off negative feelings and emotions by controlling your thoughts. By blocking undesirable thoughts, you allow your subconscious mind to absorb your good thoughts. This can help you develop a plan to achieve your purpose, goals, and desires.",
  151: "Think positively! Negative thoughts and impulses combined with emotions can negatively “infect” your subconscious mind.",
  152: "If you “act” happy and enthusiastic, positive images will enter your mind and success will follow. The opposite is also correct.",
  153: "Block any emotion (fear, jealousy, hate, revenge, and anger) that can negatively impact your subconscious minds.",
  154: "Form a habit of focusing on positive emotions and blocking the negative ones. Achieve this through habit and repetition.",
  155: "Compare the effects of imagination and reality to achieve your goal(s). If you do this, the effects of imagination will be more powerful, because the subconscious mind is more powerful, than the conscious one.",
  156: "Don't just try. Trying is just trying. It is not doing.  Do and succeed!",
  157: "A habit is formed from repetition.",
  158: "Prayer is the key. Do not just pray when everything is failing or when you are in fear. Also, pray when you are in a good my state-of-mind and when everything is going well. This response will come into fruition as your subconscious mind develops a plan.",
  159: "Negative thoughts not only damage you, but they also damage those around you.",
  160: "Recognize that human nature is too lazy and easily influenced by negative thoughts, so keep your mind closed and away from negative influences.",
  161: "You can view your creative imagination as one of the pathways that connects your subconscious mind to your conscious one. It’s also a way for your brain to receive and send messages throughout your body.",
  162: "Positive emotions help your brain become receptive to ideas. Negative emotions have the opposite effect.",
  163: "You can send your thoughts to your subconscious mind, through positive affirmations and visualizing the person you want to be.",
  164: "Encourage your brain to have positive thoughts and discourage it to have negative ones.",
  165: "New scientific discoveries suggest that your subconscious mind uses waves to connect to the things around you. In other words, your mind interacts with things that are on the same frequency.",
  166: "Your intuition is real. It gets more accurate, the more you use it. And, that comes with practice. It is similar to subconscious mind.",
  167: "Your subconscious mind has “receivers” that allow you to read other people’s thoughts without even speaking the same language.",
  168: "Do you want to know how to join minds and create a close working alliance with your team members? The procedure is simple. Sit at a table with your team members and discuss a topic. Ask each team member to speak his or her thoughts aloud. The more frequently the team works together, the stronger the collective mind connections will be.",
  //Intuitions
  169: "Great achievements require great sacrifices.",
  170: "The more you follow your E Coaching notifications, the stronger your “sixth sense” and intuition will be.",
  171: "Use your “sixth sense” to guide you, so you know when good opportunities present themselves. View this sense as an angel guiding you.",
  172: "Follow those that inspire you and then imitate their good habits and traits.",
});
