module.exports = Object.freeze([
  "BASE_URL",
  "MONGO_DB_CONNECTION_URL",
  "JWT_SECRET_KEY",
  "SMTP_EMAIL",
  "SMTP_PASS",
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "AWS_S3_BUCKET_NAME",
  "REDIS_CONNECTION_URL",
  "STRIPE_SECRET_KEY",
  "ZEN_SERP_API",
  "APPLE_PAY_MODE",
]);
